stages:
  - build
  - deploy

.assume_role: &assume_role
    - >
      STS=($(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token $ID_TOKEN
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - export AWS_ACCESS_KEY_ID="${STS[0]}"
    - export AWS_SECRET_ACCESS_KEY="${STS[1]}"
    - export AWS_SESSION_TOKEN="${STS[2]}"

build artifact:
  stage: build
  image: node:latest
  before_script:
    - yarn
  script:
    - rm -rf apps/fancyai-web-client/src/index.html
    - mv apps/fancyai-web-client/src/index.staging.html apps/fancyai-web-client/src/index.html
    - yarn build:stage
  artifacts:
    paths:
      - build/
    when: always
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

deploy s3:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: 
      - '/usr/bin/env'
  id_tokens:
      ID_TOKEN:
        aud: fancyai_staging
  script:
    - *assume_role
    - aws s3 sync build s3://$S3_BUCKET --delete --exclude "build/index.html"
    - aws s3 cp build/index.html $S3_BUCKET/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: always